### ISSUE TITLE
How Will People Create Transit Network Sites?

### ISSUE THREAD

**Issue by vkoves** [TransitTalk/Transit-Talk#38]
Before we can let other people create their own Transit Network sites, we need to figure out the mechanism through which we will do that. Are we going to make a Ruby gem? Have people clone our app and change it (like [this Rails boilerplate](https://github.com/fdv/rails-app-boilerplate))? 

Things to consider:

- Would the solution we suggest allow for code changes?
- Do we want to be able to roll out updates to all Transit Network sites if we add new features or fix bugs?
- How technically skilled are the people spinning up new Transit Network apps?

Putting all of these questions out in the air, it seems to be me that creating a default app with a good amount of settings would be the best way to go, then letting developers fork/clone the app to customize it. This would mean that people could do pull requests back into the app and stay updated with our changes (as long as they did a fork), or choose to start with what we have and go on their own path if they clone the repository. Depending on how we want to make the license, we can decide whether people have to share improvements with us or not.

**Comment by AcademyInPeril** [comment]
Our operating assumption, so far, has been that this repo (or a similar one) would serve as "home base" for a version of the app that has stubs in place of locality-specific information, and has instructions about what coders can do to create a fully functioning implementation once they've cloned/forked. That's why all the Chicago-specific info that was once part of the repo has been cleared out.

There are a couple ways we could approach updates, but none of them are perfect. We want to give coders in individual cities the ability to modify the app to whatever extent they want, but we also want them to be able to merge in the latest updates if they wish.

We should absolutely not adopt any license that prevents anybody from doing whatever they want with the project as far as functionality goes. If major improvements are made in, say, Kansas City or Karachi, there should be no enforceable expectation that those improvements make their way back into the base project. We want to foster a community that shares such improvements naturally, but trying to put collaboration like that into license terms is scary for a potential local-scale developer and goes against the ethos of an open source project. That said, our license should be careful to place credit where it's due so that nobody runs away with our work and promotes it as their own.
